title: Lemon Studios
email: lemonptstudios@gmail.com
url: "http://www.lemonpt.com"
baseurl: "/"
instagram: https://www.instagram.com/supersamfitness/
description: >
  A bespoke personal training service, committed to results in posture, body
  composition, physical and mental state for a lifetime positive benefit.

markdown: kramdown
