title: Lemon Studios
email: team@lemonpt.co.uk
url: "http://lemonpt.co.uk"
baseurl: "/lemon-studios"
instagram: https://www.instagram.com/supersamfitness/
description: >
  Blah blah blah. Example description

markdown: kramdown
